version: "3"

services:

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    volumes:
    - /data/go-auth/mongodb:/data/db

  auth:
    build: batazor/go-auth
    container_name: auth
    restart: always
    environment:
      PORT: 4070
      MONGO_URL: mongo/auth
    ports:
    - "4070:4070"
    depends_on:
    - mongo
    volumes:
    - ./cert:/app/cert

  opentracing:
    image: jaegertracing/all-in-one:1.46.0
    container_name: opentracing
    restart: always
    ports:
    - "5775:5775/udp"
    - "16686:16686"
